spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mindvault
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true


jwt:
  secret: mindvault-super-secret-key-change-in-production-2026
  expiration: 86400000


logging:
  level:
    org.hibernate.SQL: debug
